volumes:
  user-data:

services:
  chrome:
    image: chrome
    build:
      dockerfile: docker/Dockerfile
      context: ./
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./placards:/usr/local/lib/python3.10/dist-packages/placards:ro
      - ./docker/entrypoint.sh:/entrypoint.sh:ro
      - ./config.ini:/etc/placards/config.ini:ro
      - user-data:/var/tmp/user-data
    environment:
      - DISPLAY=:0
      - XAUTH_COOKIE=${XAUTH_COOKIE}
      - PROFILE_DIR=/var/tmp/user-data
      - IGNORE_CERTIFICATE_ERRORS=true
    network_mode: host
    security_opt:
      - seccomp:unconfined
